### ISSUE TITLE
Merge clusters not working

### ISSUE THREAD

**Issue by Luc1100** [KosinskiLab/colabseg#4] opened 2024-04-20 16:26 UTC
Merge clusters does not appear to work. When I select two clusters (or more), they are highlighted in the GUI and the point cloud display. However, when I click 'Merge Clusters' nothing happens. No errors appear in the Jupyter notebook log.

**Comment by maurerv** [comment] 2024-04-20 20:32
Hi @Luc1100!

Are you using the Github or PyPi version of Colabseg?

**Comment by Luc1100** [comment] 2024-04-20 20:35
Hi @maurerv,

I am using the Github version of Colabseg i.e. I installed it using `pip install .` from the colabseg directory.

**Comment by maurerv** [comment] 2024-04-20 20:44
Great!

I just uploaded the 0.0.3 version of the code base. Could you please pull and install the newest version from GitHub?

Attached below are two screenshots of the procedure. Merging clusters 0, 1, and 2 creates the new cluster 11, which is appended to the end of the list. 

![Screenshot 2024-04-20 at 22 39 09](https://github.com/KosinskiLab/colabseg/assets/43959863/c8a48e40-0416-4306-a68d-4a3a49a0d9f5)
![Screenshot 2024-04-20 at 22 39 20](https://github.com/KosinskiLab/colabseg/assets/43959863/c4ae505e-4234-492a-9112-16dc14735dd7)

**Comment by Luc1100** [comment] 2024-04-20 21:18
It is working now! Thank you for the quick fix!

**Comment by maurerv** [comment] 2024-04-20 21:21
Great to hear!

I will go ahead and close this issue, feel free to re-open or create a new issue should you run into any complications

**Closed as completed by maurerv** 2024-04-20 21:21 UTC

**Comment by Luc1100** [comment] 2024-04-22 18:29
Hi @maurerv,

I just installed the latest GitHub version of ColabSeg on another computer and merging clusters seems to have broken again in the newest version that incorporates MemBrain-seg functionality.

Edit: On the 0.0.3 version I am not sure what causes it but sometimes merging does not work until the kernel is restarted and the data is reloaded. I did a couple rounds of clustering and merging and then randomly I was unable to merge clusters anymore.

Edit 2: This actually appears to be an issue with Jupyter notebook UI over ssh as the viewer also started acting weird. The same version ran locally seems to work fine.

**Comment by maurerv** [comment] 2024-04-22 19:52
Hi @Luc1100,

Thanks for reporting this. 

Unfortunately, the widgets used by colabseg are very sensitive to the version of jupyter and associated software. As a result, it's possible that not everything works as intended with the jupyter over ssh setup. Personally, I usually compress segmentations using gzip, transfer them to my local PC, and then read the compressed files using colabseg. Even for large tomograms, the size of gzip-compressed segmentations rarely exceeds a few megabytes.

 I'll make sure to keep an eye out for similar patterns next time I work on my segmentations :)

**Comment by Luc1100** [comment] 2024-04-22 19:54
I figured it was something that would not really be fixable once I realized the pattern, thanks for the suggestion :)

**Comment by kimdn** [comment] 2024-06-16 07:50
> Hi @Luc1100,
> 
> Thanks for reporting this.
> 
> Unfortunately, the widgets used by colabseg are very sensitive to the version of jupyter and associated software. As a result, it's possible that not everything works as intended with the jupyter over ssh setup. Personally, I usually compress segmentations using gzip, transfer them to my local PC, and then read the compressed files using colabseg. Even for large tomograms, the size of gzip-compressed segmentations rarely exceeds a few megabytes.
> 
> I'll make sure to keep an eye out for similar patterns next time I work on my segmentations :)

Thank you for releasing awesome tool!

For your troubleshooting/debug, I share what versions I use
 "jupyter notebook  : 6.5.2 and python 3.8". 

I can't merge clusters as well (I can delete cluster well though).
